# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 129aaf42a7899f8fbb2f745dcd80e37e88a8aac2e4c813da3c44edcdaba2295b1d87d73e8c6cd552ee5236bbeb401fe77b489bd5ea2b0ee5e467ffdb767ecb0b

test:
  secret_key_base: 9586d265e0472479c9649e512a22b3051e991369374f23f1db0b1cfedfa43aa71ac6dc912c4de76399e61f24b6dd01dd582717bb204c0e07cf10246cc692af28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
